# Generated by Django 3.0.2 on 2020-01-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stockNo', models.IntegerField()),
                ('releaseDate', models.DateField()),
                ('specs', models.FileField(upload_to='media/media/documents/')),
                ('image', models.ImageField(upload_to='media/media/images/')),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productmanagement.Product')),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productmanagement.Product')),
                ('screenSize', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=60)),
                ('RAM', models.CharField(max_length=255)),
                ('ROM', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=60)),
                ('cpu', models.CharField(max_length=255)),
                ('graphics', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('screenSize', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=60)),
                ('RAM', models.CharField(max_length=255)),
                ('ROM', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productmanagement.Product')),
            ],
        ),
    ]
