# Generated by Django 2.2.7 on 2020-02-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
        ('orderManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='productmanagement.Product'),
        ),
    ]
